version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: swiftmailer/swiftmailer
    versions:
    - 6.2.6
  - dependency-name: tracy/tracy
    versions:
    - 2.8.2
